def append_to_ai_tools_panel():
    filepath = 'mathlab/ui/ai_tools_panel.py'
    with open(filepath, 'a', encoding='utf-8') as f:
        f.write('\n')
        f.write('    def on_ai_generate_request(self, user_prompt):\n')
        f.write('        from mathlab.core.ai_manager import MathAgent\n')
        f.write('        from mathlab.core.async_workers import TaskWorker\n')
        f.write('        from PySide6.QtCore import QThreadPool\n')
        f.write('        if not hasattr(self, "ai_agent"):\n')
        f.write('            self.ai_agent = MathAgent()\n')
        f.write('        \n')
        f.write('        # 1. 开启子线程调用 Agent，防止 UI 卡顿\n')
        f.write('        worker = TaskWorker(self.ai_agent.solve_problem, user_prompt)\n')
        f.write('        \n')
        f.write('        def on_complete(result):\n')
        f.write('            if result["status"] != "failed":\n')
        f.write('                # 自动将代码填入 Monaco 编辑器\n')
        f.write('                self.code_editor.set_code(result["code"])\n')
        f.write('                # 在控制台显示结果\n')
        f.write('                if hasattr(self, "output_area"):\n')
        f.write('                    self.output_area.append(str(result["result"]))\n')
        f.write('                elif hasattr(self, "console"):\n')
        f.write('                    self.console.append(str(result["result"]))\n')
        f.write('        \n')
        f.write('        worker.signals.result.connect(on_complete)\n')
        f.write('        QThreadPool.globalInstance().start(worker)\n')

append_to_ai_tools_panel()
print("Appended on_ai_generate_request to ai_tools_panel.py")
